config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  resources :posts do 
    resources :comments
  end

  devise_for :admins
  root to: "posts#index"


  
  # # resources :admin
  # resources :admins do
  #   resources :posts
  # end


  
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # has_secure_password
  has_many :posts, class_name: "post", foreign_key: "reference_id", dependent: :destroy
  has_many :comments , foreign_key: "reference_id"
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email ,uniqueness: true
  has_many :comments, class_name: "comment", foreign_key: "reference_id"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :admin
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :admin
  has_many :comments 
  has_one_attached :image
  validates :image ,presence: true
  validates :title, presence: true
  validates :main ,presence: true

   # has_secure_password
  #  devise :database_authenticatable, :registerable,
  #         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def authenticate_user!
      @post = Post.find(params[:id])
      @comment = Comment.find(params[:id])
         unless admin_signed_in?
          redirect_to new_admin_session_path, :alert => "You are not authorized to access this page."
            
         end
        end 
  

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show  ]
  before_action :authenticate_user!, only: %i[create, update, destroy,edit]
  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:remark, :post_id, :admin_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user! , only: %i[create destroy update edit]
  before_action :set_post, only: %i[ show  destroy ]


  # GET /posts or /posts.json
  def index
    @posts = Post.all
    @current_weather = Accuweather.get_conditions(location_id: 'cityId:53286').current
    
  end

  # GET /posts/1 or /posts/1.json
  def show
     @comments = @post.comments.all
     
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
     
    end

    # Only allow a list of trusted parameters through.
    def post_params
      
      params.require(:post).permit(:title, :image, :main, :admin_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Remark:</strong>
    <%= comment.remark %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= comment.post_id %>
  </p>

  <p>
    <strong>Admin:</strong>
    <%= comment.admin_id %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div id="new_comment">
  <div>
    <%= form.label :remark, style: "display: block" %>
    <%= form.text_field :remark  %>
  </div>

  <div>
    <%=form.label :post_id, style: "display: block" %>
    <%=form.text_field :post_id  ,value: params[:post_id]%>
  </div>

  <div>
    <%=form.label :admin_id, style: "display: block" %>
    <%= form.text_field :admin_id  ,value: current_admin.id%>
  </div>

  <div>
    <%= form.submit %>
    
  </div> </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments_partial">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment ,id:"commnets_partial" %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>STRANGE</title>
    <%= favicon_link_tag "first.png"%>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application","devise" ,"data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "devise", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
  
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-white" data-spy="affix" data-offset-top="510">
        <div class="container">
            <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse mt-sm-20 navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a href="#home" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="#about" class="nav-link">About</a>
                    </li>
                    <li class="nav-item">
                          <%= link_to "Post" ,posts_path    ,class:"nav-link" %>
                       
                       
                    </li>
                </ul>
                <ul class="navbar-nav brand">
                   
                    <li class="brand-txt">
                       
                        <div class="brand-subtitle">Web Designer | Developer</div>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                     <% unless current_admin %>
                         <%# <a href="127.0.0.1:3000/admins/sign_up" class="nav-link">Login</a> %>
                          <%= link_to "Login" ,new_admin_session_path     ,class:"nav-link" %>
                          <%end%>
                    </li>
                    <li class="nav-item">
                    <% unless current_admin %>
                          <a href="http://127.0.0.1:3000/admins/sign_up" , class="nav-link" >Sign Up</a>
                        <%end%>
                    </li>
                    <% if admin_signed_in? %>
                    <li class="nav-item last-item">
                        <%= link_to "Logout" ,destroy_admin_session_path ,class:"nav-link" %>
                        
                    </li>
                    <li class="nav-item last-item">
                    <%x= current_admin.email%>
                        <%= link_to x , admin_session_path,class:"nav-link" %>
                        
                    </li>

                    <% end%>
                </ul>
            </div>
        </div>
    </nav>
     <%= yield %>
   
   


   
    <div class="section contact" id="contact">
        <div id="map" class="map"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="contact-form-card">
                        <h4 class="contact-title">Send a message</h4>
                        <form action="">
                            <div class="form-group">
                                <input  class="form-control" type="text" placeholder="Name *" required>
                            </div>
                            <div class="form-group">
                                <input class="form-control" type="email" placeholder="Email *" required>
                            </div>
                            <div class="form-group">
                                <textarea class="form-control" id=" placeholder="Message *" rows="7" required></textarea>
                            </div>
                            <div class="form-group ">
                                <button type="submit" class="form-control btn btn-primary" >Send Message</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="contact-info-card">
                        <h4 class="contact-title">Get in touch</h4>
                        <div class="row mb-2">
                            <div class="col-1 pt-1 mr-1">
                                <i class="ti-mobile icon-md"></i>
                            </div>
                            <div class="col-10 ">
                                <h6 class="d-inline">Phone : <br> <span class="text-muted">+91 </span></h6>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-1 pt-1 mr-1">
                                <i class="ti-map-alt icon-md"></i>
                            </div>
                            <div class="col-10">
                                <h6 class="d-inline">Address :<br> <span class="text-muted">Sec 5, PKL</span></h6>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-1 pt-1 mr-1">
                                <i class="ti-envelope icon-md"></i>
                            </div>
                            <div class="col-10">
                                <h6 class="d-inline">Email :<br> <span class="text-muted">abc@gmail.com</span></h6>
                            </div>
                        </div>
                        <ul class="social-icons pt-4">
                            <li class="social-item"><a class="social-link text-dark" href="#"><i class="ti-facebook" aria-hidden="true"></i></a></li>
                            <li class="social-item"><a class="social-link text-dark" href="#"><i class="ti-twitter" aria-hidden="true"></i></a></li>
                            <li class="social-item"><a class="social-link text-dark" href="#"><i class="ti-google" aria-hidden="true"></i></a></li>
                            <li class="social-item"><a class="social-link text-dark" href="#"><i class="ti-instagram" aria-hidden="true"></i></a></li>
                            <li class="social-item"><a class="social-link text-dark" href="#"><i class="ti-github" aria-hidden="true"></i></a></li>
                        </ul> 
                    </div>
                </div>
            </div>

        </div>
    </div>
    <footer class="footer py-3">
        <div class="container">
           
        </div>
    </footer>

	
    
    

   
  </body>
</html>

app/views/posts/_comments.html.erb
<p style="color: green"><%= notice %></p>

<h1 style="color: danger;  margin-left:7%;">Comments</h1><br>
<%= link_to "New comment", new_post_comment_path(@post) ,style:"margin-left:10%;",id:"destroy_button"%>
<br><br>
<div id="comments_partial">

  <% @comments.each do |comment| %>
    <%= comment.remark %><%x=comment.admin_id%>
    <br>
    <%=Admin.find(x).email%>

    <p>
      <%= link_to "Show this comment", comment %>

    </p>
    <hr>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 

 <div class="form_align" >
  
  <div >
  
    <%# <%= form.label :title, style: "display: block" %> 
    <%= form.text_field :title ,placeholder: "Title", id:"new_form_title"%>
  </div>

<hr>
  <div>
        IMAGE: <p id="form_image_upload"><%= form.file_field :image %></p>
    <%# <%= form.label :image, style: "display: block" ,id:"new_form_image" %> 
    
  </div>

  <div>
    <%# <%= form.label :main, style: "display: block" %>
    <%= form.text_area :main  , placeholder: "Content" ,id:"new_form_content" %>
  </div>

  <div id="admin_id_form" >
   <%if admin_signed_in?%>
     <% x=current_admin.id%>
    <p style="margin-left:2%;"> Current Admin ID:  <%= form.text_field :admin_id ,value: x%></p>
    <%end%>
    
   
    
  </div>

  <div>
    <%= form.submit %>
  </div>


  </div>
<% end %>

app/views/posts/_form1.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :remark, style: "display: block" %>
    <%= form.text_field :remark  %>
  </div>

  <div>
    <%= form.label :post_id, style: "display: block" %>
    <%= form.text_field :post_id  ,value: params[:post_id]%>
  </div>

  <div>
    <%= form.label :admin_id, style: "display: block" %>
    <%= form.text_field :admin_id  ,value: current_admin.id%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_head.html.erb
<a href="components.html" class="btn btn-primary btn-component" data-spy="affix" data-offset-top="600"><i class="ti-shift-left-alt"></i> Components</a>
    <header class="header">
        <div class="container">
            <ul class="social-icons pt-3">
                <li class="social-item"><a class="social-link text-light" href="#"><i class="ti-facebook" aria-hidden="true"></i></a></li>
                <li class="social-item"><a class="social-link text-light" href="#"><i class="ti-twitter" aria-hidden="true"></i></a></li>
                <li class="social-item"><a class="social-link text-light" href="#"><i class="ti-google" aria-hidden="true"></i></a></li>
                <li class="social-item"><a class="social-link text-light" href="#"><i class="ti-instagram" aria-hidden="true"></i></a></li>
                <li class="social-item"><a class="social-link text-light" href="#"><i class="ti-github" aria-hidden="true"></i></a></li>
            </ul>  
            <div class="header-content">
                <h4 class="header-subtitle" ></h4>
                <h1 class="header-title">STRANGE</h1>
                <h6 class="header-mono" >Blogs | Stories</h6>
                <iframe width="560" height="315" src="https://www.youtube.com/embed/mGZz1FCb6z4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                <button class="btn btn-primary btn-rounded"><i class="ti-printer pr-2"></i><a href="/posts">SIGN UP</a></button>
            </div>
        </div>
    </header>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= link_to post.image.filename, post.image if post.image.attached? %>
  </p>

  <p>
    <strong>Main:</strong>
    <%= post.main %>
  </p>

  <p>
    <strong>Admin:</strong>
    <%= post.admin_id %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<%= render "head"%>
<%# <%= @current_weather%> %>
 <section class="section" id="blog">
        <div class="container">
            <h2 class="mb-5">Latest <span class="text-danger">Post</span></h2>
            <div class="row">
                <div class="blog-card">
                    <div class="img-holder">
                    
            <% @posts.each do |post| %>
                
                  <h1 class="index_image">
                    <%= image_tag post.image%></h1>
            
                  
                    <div class="content-holder">

                        <h6 class="title"><%=link_to post.title ,post%></h6>

                        <p class="post-details">
                         <%x=post.admin_id%> 
                         <%c=Admin.find(x)%>
                            <a href="#">By: <%=c.email%>  || Likes: </a>
                            
                        </p>
                        
                        <p><%= post.main.truncate(50)%></p>

                       <%=link_to "Read more" ,post%>
                       <hr>
                        <br>
                        <%end%>
                        
                    </div>
                </div>
               
              

            </div>
        </div>
         
    </section>
    <% if admin_signed_in?%>
                <div class="button_link">
               <%= link_to "New post", new_post_path , id:"destroy_button",style:"margin-left:40%;"%></div>
               <%end%>

app/views/posts/new.html.erb
<br>
<br>
<h2  id="new_post_heading" ,class="mb-5">New <span class="text-danger">Post</span></h2>

<%= render "form", post: @post %>

<br>

<div>


  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<br><br>
<div id="show_post_title">
<%=  @post.title %></div>
<br>
<%= image_tag @post.image ,id:"post_image"%>
<div class="post_show_main">
<%= @post.main%></div>

<div style="text-align:center;"> 
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %></div><div>
  <%if admin_signed_in?%>
  <%=link_to "Add a comment" ,new_post_comment_path(@post)%>
      <% if current_admin.id==@post.admin_id%>
  
        <%= button_to "Destroy this post", @post, method: :delete ,id:"destroy_button"%>
      <% end %>
      <%end%>

  <%post = Post.find(@post.id)%>
  
  <%= time_ago_in_words(post.created_at)%> ago created.
  <%# <%= render 'comments/form'%> 

  <%= render 'comments'%>
  <br>
  
  
  
</div>